# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='New Game', max_length=256),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='executor_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
